### ISSUE TITLE
Styling visible on featured article section

### ISSUE THREAD

**Issue by yashwanth944** [wikimedia/wikipedia-ios-lite#2]
On featured article section,
Styling is visible to the end user.
Please find the details in the attached screenshot.![image](https://user-images.githubusercontent.com/20689246/155225170-953eb523-0e09-4bdd-a022-86b19f6e3d2b.png)

**Comment by tonisevener** [comment]
@yashwanth944 thanks for reporting this bug! We added it to our task tracking software, Phabricator. You can follow our progress at the link [here](https://phabricator.wikimedia.org/T302612).

Just for future reference - this repository is actually an unused prototype repo. You can report future bugs through the app via app Settings > Help and Feedback > Report a bug, or alternatively you can email mobile-ios-wikipedia@wikimedia.org directly. Thanks!
